name: Host on Vercel

on:
    pull_request:
        branches: main
        types: [opened, reopened, synchronize]
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              
            - name: Wait for Main CI/CD
              if: github.base_ref == 'main'
              uses: fountainhead/action-wait-for-check@v1.2.0
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  checkName: integrity-check
                  intervalSeconds: 30
                  timeoutSeconds: 600
                  ref: ${{ github.event.pull_request.head.sha }}

            - name: Deploy to Vercel Action
              uses: BetaHuhn/deploy-to-vercel-action@v1.10.0

              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
                  GITHUB_DEPLOYMENT: false
                  PR_LABELS: Deployed
