name: Deploy to Vercel

on:
    pull_request:
        branches: main
        types: [opened, reopened, synchronize]
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Wait for Main CI/CD
              uses: fountainhead/action-wait-for-check@v1.2.0
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  checkName: integrity-check
                  intervalSeconds: 30
                  timeoutSeconds: 600
                  ref: ${{ github.event.pull_request.head.sha }}

            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.ACTION_PAT }}

            - name: Setup PNPM
              uses: pnpm/action-setup@v4
              with:
                  version: latest

            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version-file: '/project/.node-version'
                  cache: 'pnpm'
                  cache-dependency-path: 'project/pnpm-lock.yaml'

            - name: Install Dependencies
              working-directory: ./project
              run: pnpm install --frozen-lockfile

            - name: Build
              id: build
              working-directory: ./project
              run: pnpm run build

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              if: steps.build.outcome == 'success'
              with:
                  name: build
                  path: ${{ github.workspace }}/project/.next/
                  retention-days: 7
                  overwrite: true
                  include-hidden-files: true
    vercel:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Download build artifacts
              uses: actions/download-artifact@v4
              with:
                  name: build
                  path: ${{ github.workspace }}/project/.vercel/output
                  github-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Deploy to Vercel Action
              uses: shehroze-1122/deploy-to-vercel-action@v2.0.0
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
                  PREBUILT: true
                  PR_LABELS: Deployed

            - name: Delete artifacts
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'
              uses: geekyeggo/delete-artifact@v5
              with:
                  name: build
