name: Deploy to Vercel

on:
    pull_request:
        branches: main
        types: [opened, reopened, synchronize]
    push:
        branches:
            - main

jobs:
    vercel:
        runs-on: ubuntu-latest
        steps:
            - name: Wait for build artifacts
              if: github.event_name == 'pull_request' && github.base_ref == 'main'
              uses: fountainhead/action-wait-for-check@v1.2.0
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  checkName: Upload build artifacts
                  ref: ${{ github.event.pull_request.head.sha }}

            - name: Download build artifacts
              uses: actions/download-artifact@v4
              with:
                    name: build-output
                    path: ${{ github.workspace }}/project/.next/

            - name: Deploy to Vercel Action
              uses: shehroze-1122/deploy-to-vercel-action@v2.0.0
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
                  PREBUILT: true
                  WORKING_DIRECTORY: ${{ github.workspace }}/project/.next/
                  PR_LABELS: Deployed

            - name: Delete artifacts
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'
              uses: geekyeggo/delete-artifact@v5
              with:
                  name: build-output
