name: Deploy CI
on:
    pull_request:
        branches: [main, Preview]
        types: [opened, reopened, synchronize]

jobs:
    vercel:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Deploy to Vercel Action
              uses: shehroze-1122/deploy-to-vercel-action@v2.0.0
              with:
                  WORKING_DIRECTORY: ./project
                  GITHUB_TOKEN: ${{ secrets.ACTION_PAT }}
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
                  BUILD_ENV: |
                      FOO="bar"
                      SOME_TOKEN="${{ secrets.SOME_TOKEN }}"
