name: Deploy to Vercel

on:
    workflow_run:
        workflows: ['Main CI/CD']
        types:
            - completed
        branches:
            - main

jobs:
    vercel:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Download build artifacts
              uses: actions/download-artifact@v4
              with:
                  name: build-output
                  path: project/.next

            - name: Deploy to Vercel Action
              uses: shehroze-1122/deploy-to-vercel-action@v2.0.0
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
                  PREBUILT: true
                  WORKING_DIRECTORY: project

            - name: Delete artifacts
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'
              uses: geekyeggo/delete-artifact@v5
              with:
                  name: build-output
