name: Deploy to Vercel

on:
    pull_request:
        branches: main
        types: [opened, reopened, synchronize]
    push:
        branches:
            - main

jobs:
    vercel:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Deploy to Vercel Action
              uses: shehroze-1122/deploy-to-vercel-action@v2.0.0
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
