name: Dev PR
on:
    pull_request:
        types: [opened, reopened, synchronize]
        branches:
            - Dev

permissions:
    contents: write
    pull-requests: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: latest

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version-file: '/project/.node-version'
                  cache: 'pnpm'
                  cache-dependency-path: 'project/pnpm-lock.yaml'

            - name: Install dependencies
              working-directory: ./project
              run: pnpm install

            - name: Build
              working-directory: ./project
              run: pnpm build

    dependabot:
        name: 'Dependabot'
        needs: [build]
        runs-on: ubuntu-latest
        if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
        steps:
            - name: Enable auto-merge for Dependabot PRs
              run: |
                  if ! gh pr merge --auto --merge "$PR_URL"; then
                    echo "Merge failed, attempting rebase..."
                    gh pr merge --auto --rebase "$PR_URL"
                  fi
              env:
                  PR_URL: ${{github.event.pull_request.html_url}}
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
