name: Restrict PRs to Preview and Main

on:
    pull_request:
        branches:
            - Preview
            - Main

jobs:
    restrict-prs:
        runs-on: ubuntu-latest
        steps:
            - name: Check branch
              if: github.event_name == 'pull_request'
              run: |
                  if [ "${GITHUB_BASE_REF}" == "Preview" ] && [ "${GITHUB_HEAD_REF}" != "Dev" ]; then
                    echo "::error::Only the 'Dev' branch can make a pull request to the 'Preview' branch."
                    exit 1
                  elif [ "${GITHUB_BASE_REF}" == "Main" ] && [ "${GITHUB_HEAD_REF}" != "Preview" ]; then
                    echo "::error::Only the 'Preview' branch can make a pull request to the 'Main' branch."
                    exit 1
                  fi
